"""Executable regression test for INC-002.

Generated by Pulse Regression Test Generator.
Failure Type: pagination_stalled
Summary: Pagination halted on page(s) [2]. Page repeated previously observed records.
Recommended Action: Inspect page progression and pagination state advancement in adapter.
"""

from pathlib import Path

import pulse
from pulse.contracts.models import InvariantType
from pulse.replay.recorder import load_run_trace
from pulse.verification.engine import VerificationEngine

_repo_root = Path(pulse.__file__).resolve().parent.parent.parent
INCIDENT_DIR = _repo_root / "incidents" / "INC-002"
if not INCIDENT_DIR.exists():
    INCIDENT_DIR = Path.cwd() / "incidents" / "INC-002"


def test_inc_002_fails_before_repair():
    """Verify that the unpatched incident trace fails deterministic verification."""
    trace = load_run_trace(INCIDENT_DIR / "trace.json")
    engine = VerificationEngine()
    report = engine.verify(trace, incident_id="INC-002")

    assert report.status == "FAILED", "Unpatched trace must fail verification"
    assert InvariantType.PAGINATION_CONTINUITY in report.failed_invariants, (
        f"Expected { InvariantType.PAGINATION_CONTINUITY } to be violated, got {report.failed_invariants}"
    )


def test_inc_002_passes_after_repair():
    """Verify that after repair logic is applied, the trace satisfies all invariants."""
    trace = load_run_trace(INCIDENT_DIR / "trace.json")

    # Apply repair logic matching the incident classification
    # Repair: eliminate repeated pagination and deduplicate records
    unique_records = []
    seen = set()
    for rec in trace.records:
        if rec.source_listing_id not in seen:
            seen.add(rec.source_listing_id)
            unique_records.append(rec)
    trace.records = unique_records
    # Ensure requests reflect progressing pages
    for i, req in enumerate(trace.requests):
        req.raw_payload = f"unique_payload_{i}"

    engine = VerificationEngine()
    repaired_report = engine.verify(trace, incident_id="{incident_id}")
    assert repaired_report.status == "PASSED", f"Repaired trace must pass, got {repaired_report.summary}"
