"""Executable regression test for INC-001.

Generated by Pulse Regression Test Generator.
Failure Type: limit_overrun
Summary: Requested limit of 20 was exceeded by 20 records across 2 requests.
Recommended Action: Enforce requested limit boundary and slice accumulated records before returning.
"""

from pathlib import Path

import pulse
from pulse.contracts.models import InvariantType
from pulse.replay.recorder import load_run_trace
from pulse.verification.engine import VerificationEngine

_repo_root = Path(pulse.__file__).resolve().parent.parent.parent
INCIDENT_DIR = _repo_root / "incidents" / "INC-001"
if not INCIDENT_DIR.exists():
    INCIDENT_DIR = Path.cwd() / "incidents" / "INC-001"


def test_inc_001_fails_before_repair():
    """Verify that the unpatched incident trace fails deterministic verification."""
    trace = load_run_trace(INCIDENT_DIR / "trace.json")
    engine = VerificationEngine()
    report = engine.verify(trace, incident_id="INC-001")

    assert report.status == "FAILED", "Unpatched trace must fail verification"
    assert InvariantType.LIMIT_BOUND in report.failed_invariants, (
        f"Expected { InvariantType.LIMIT_BOUND } to be violated, got {report.failed_invariants}"
    )


def test_inc_001_passes_after_repair():
    """Verify that after repair logic is applied, the trace satisfies all invariants."""
    trace = load_run_trace(INCIDENT_DIR / "trace.json")

    # Apply repair logic matching the incident classification
    # Repair: slice accumulated records to declared limit bound
    if trace.requested_limit and len(trace.records) > trace.requested_limit:
        trace.records = trace.records[:trace.requested_limit]

    engine = VerificationEngine()
    repaired_report = engine.verify(trace, incident_id="{incident_id}")
    assert repaired_report.status == "PASSED", f"Repaired trace must pass, got {repaired_report.summary}"
