"""Executable regression test for INC-003.

Generated by Pulse Regression Test Generator.
Failure Type: silent_zero_yield
Summary: HTTP request succeeded with substantial payload, but parser yielded 0 records.
Recommended Action: Inspect upstream payload structure and update JSON key or HTML selector paths in extract_raw_records.
"""

from pathlib import Path
import pulse
from pulse.contracts.models import InvariantType
from pulse.replay.recorder import load_run_trace
from pulse.verification.engine import VerificationEngine

_repo_root = Path(pulse.__file__).resolve().parent.parent.parent
INCIDENT_DIR = _repo_root / "incidents" / "INC-003"
if not INCIDENT_DIR.exists():
    INCIDENT_DIR = Path.cwd() / "incidents" / "INC-003"


def test_inc_003_fails_before_repair():
    """Verify that the unpatched incident trace fails deterministic verification."""
    trace = load_run_trace(INCIDENT_DIR / "trace.json")
    engine = VerificationEngine()
    report = engine.verify(trace, incident_id="INC-003")

    assert report.status == "FAILED", "Unpatched trace must fail verification"
    assert InvariantType.ZERO_YIELD in report.failed_invariants, (
        f"Expected { InvariantType.ZERO_YIELD } to be violated, got {report.failed_invariants}"
    )


def test_inc_003_passes_after_repair():
    """Verify that after repair logic is applied, the trace satisfies all invariants."""
    trace = load_run_trace(INCIDENT_DIR / "trace.json")

    # Apply repair logic matching the incident classification
    # Repair: extract records from mutated payload structure
    from pulse.adapters.nextimmo import NextimmoAdapter
    import json, re
    adapter = NextimmoAdapter()
    for req in trace.requests:
        payload = req.raw_payload or ""
        # Match data container in mutated structure
        m = re.search(r'class="results-v2">(.*?)</div>', payload)
        if m:
            raw_items = json.loads(m.group(1))
            trace.records = [adapter.normalize_record(r) for r in raw_items]

    engine = VerificationEngine()
    repaired_report = engine.verify(trace, incident_id="{incident_id}")
    assert repaired_report.status == "PASSED", f"Repaired trace must pass, got {repaired_report.summary}"
