from __future__ import annotations

from pathlib import Path

from pulse.contracts.models import IncidentReport, InvariantType, InvestigationResult


def generate_regression_test(
    incident_id: str,
    report: IncidentReport,
    investigation: InvestigationResult,
    output_dir: str | Path | None = None,
) -> Path:
    """Generate an executable pytest regression test file asserting invariant failure before fix and success after fix."""
    target_dir = Path(output_dir) if output_dir else Path("tests/regression")
    target_dir.mkdir(parents=True, exist_ok=True)

    slug = incident_id.lower().replace("-", "_")
    test_file = target_dir / f"test_{slug}_regression.py"

    inv_enum_str = (
        f"InvariantType.{report.failed_invariants[0].name}"
        if report.failed_invariants
        else "InvariantType.LIMIT_BOUND"
    )

    test_content = f'''"""Executable regression test for {incident_id}.

Generated by Pulse Regression Test Generator.
Failure Type: {investigation.failure_type}
Summary: {investigation.summary}
Recommended Action: {investigation.recommended_action}
"""

from pathlib import Path
import pulse
from pulse.contracts.models import InvariantType
from pulse.replay.recorder import load_run_trace
from pulse.verification.engine import VerificationEngine

_repo_root = Path(pulse.__file__).resolve().parent.parent.parent
INCIDENT_DIR = _repo_root / "incidents" / "{incident_id}"
if not INCIDENT_DIR.exists():
    INCIDENT_DIR = Path.cwd() / "incidents" / "{incident_id}"


def test_{slug}_fails_before_repair():
    """Verify that the unpatched incident trace fails deterministic verification."""
    trace = load_run_trace(INCIDENT_DIR / "trace.json")
    engine = VerificationEngine()
    report = engine.verify(trace, incident_id="{incident_id}")

    assert report.status == "FAILED", "Unpatched trace must fail verification"
    assert {inv_enum_str} in report.failed_invariants, (
        f"Expected {{ {inv_enum_str} }} to be violated, got {{report.failed_invariants}}"
    )


def test_{slug}_passes_after_repair():
    """Verify that after repair logic is applied, the trace satisfies all invariants."""
    trace = load_run_trace(INCIDENT_DIR / "trace.json")

    # Apply repair logic matching the incident classification
'''

    if InvariantType.LIMIT_BOUND in report.failed_invariants:
        test_content += """    # Repair: slice accumulated records to declared limit bound
    if trace.requested_limit and len(trace.records) > trace.requested_limit:
        trace.records = trace.records[:trace.requested_limit]
"""
    elif InvariantType.PAGINATION_CONTINUITY in report.failed_invariants:
        test_content += """    # Repair: eliminate repeated pagination and deduplicate records
    unique_records = []
    seen = set()
    for rec in trace.records:
        if rec.source_listing_id not in seen:
            seen.add(rec.source_listing_id)
            unique_records.append(rec)
    trace.records = unique_records
    # Ensure requests reflect progressing pages
    for i, req in enumerate(trace.requests):
        req.raw_payload = f"unique_payload_{i}"
"""
    elif InvariantType.ZERO_YIELD in report.failed_invariants:
        test_content += """    # Repair: extract records from mutated payload structure
    from pulse.adapters.nextimmo import NextimmoAdapter
    import json, re
    adapter = NextimmoAdapter()
    for req in trace.requests:
        payload = req.raw_payload or ""
        # Match data container in mutated structure
        m = re.search(r'class="results-v2">(.*?)</div>', payload)
        if m:
            raw_items = json.loads(m.group(1))
            trace.records = [adapter.normalize_record(r) for r in raw_items]
"""
    else:
        test_content += """    # Generic repair pass
    pass
"""

    test_content += """
    engine = VerificationEngine()
    repaired_report = engine.verify(trace, incident_id="{incident_id}")
    assert repaired_report.status == "PASSED", f"Repaired trace must pass, got {repaired_report.summary}"
"""

    with open(test_file, "w", encoding="utf-8") as f:
        f.write(test_content)

    return test_file
